version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    container_name: financial_report
    volumes:
      - .:/var/www/html
      - laravel_storage_public:/var/www/html/storage/app/public
    command: >
      sh -c "php artisan key:generate --force &&
            php artisan migrate --force &&
            php artisan storage:link &&
            chmod -R 777 storage bootstrap/cache public/storage &&
            php-fpm"

volumes:
  laravel_storage_public:
