version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    container_name: financial_report
    volumes:
      - .:/var/www/html
    command: >
      sh -c "php artisan key:generate --force &&
            php artisan migrate --force &&
            php artisan serve --host=0.0.0.0 --port=9000"

